name: MinecraftDiscordConnect
version: 1.0.4_1
author: Sorp
authors: [Sorp, Ashimara]
website: https://github.com/sorp123/MinecraftDiscordConnect
main: eu.sorp.minecraftdiscordconnect.MinecraftDiscordConnect
load: STARTUP
commands:
  discord:
    description: Handles the connection of your Discord Bot
    permission: minecraftdiscordconnect.command.discord.connections
    usage: /discord <connect/disconnect>
  channelids:
    description: Edits your ChannelIDs
    permission: minecraftdiscordconnect.command.discord.channelids
    usage: /channelids <send/recieve> <ChannelIDs...>
  